she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name= 'story'),
    path('add-story/', views.AddStoryView.as_view(),name='newStory'),
    # path('update-story/', views.UpdateStoryView.as_view(), name='updateStory')
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include ('django.contrib.auth.urls')), #/login and /logout
    path('users/', include ('users.urls'))    
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView
from .views import ProfileView

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(),name='createAccount'),
    path('<int:pk>/', ProfileView.as_view(), name='Profile' )
]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey (
        get_user_model(),
        on_delete = models.CASCADE
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    image_url = models.TextField(default="")

    class Meta:
        ordering = ["pub_date"]

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
    pass

    def __str__(self): #when i look at a self - so an instance of the class above, it will reformat it
        return self.username

she_codes_news/news/forms.py
from django import forms #to use all the super cool django form stuff
from django.forms import ModelForm
from .models import NewsStory


class StoryForm(ModelForm):
    class Meta: 
        #nested class we want django to infer from
        model = NewsStory
        #list of fields to be included in the form
        fields = ['title', 'pub_date', 'content'] 
        widgets = {
            'pub_date': forms.DateInput(format=('%m/%d/%Y'),
            attrs={"class":"form-control", 
            "placeholder":"Select a date",
            "type":"date"})
}

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta: 
        model = CustomUser
        fields = ['username', 'email']

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']

she_codes_news/news/views.py
from django.views import generic
from .models import NewsStory
from .forms import StoryForm
from django.urls import reverse_lazy


class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.order_by("pub_date")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all()[:4]
        context['all_stories'] = NewsStory.objects.all()
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index') #we use the name we called the path in urlpatterns to get the url path

    def form_valid(self, form): #set author to user logged in
        form.instance.author = self.request.user
        return super().form_valid(form) #overriding form_valid which is a generic.createView

# class UpdateStoryView(generic.UpdateView):
#     form_class = UpdateStoryForm
#     model = NewsStory
#     template_name = 'news/updateStory.html'

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic

from .models import CustomUser
from .forms import CustomUserCreationForm
from news.models import NewsStory

# Create your views here.

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

class ProfileView(generic.DetailView):
    model = CustomUser
    template_name = 'users/profile.html'
    context_object_name = 'user'

she_codes_news/news/templates/news/createStory.html
{% extends 'base.html' %}

{% block content %}
<div id="new-story-container">
    <h2>New Story</h2>
    <form action="" method="POST">
        {% csrf_token %} <!-- cross site anti forgery -->
        {{ form.as_p }} <!-- double curly can host a string -->
        <div class="button-div">
            <input id= "submit" type="submit" value="Post story!">
        </div>
    </form>
    </div>


{% endblock content %}

she_codes_news/news/templates/news/index.html
{% extends 'base.html'%}
{% load static %}
    
{% block content%}
        <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %} 
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
        {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>
{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}" >
{% endblock %}

{% block content %}

<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>{{ story.author }}</h4>
    
    <div id="story-content">
        {% if '<int:pk>/' < 4 %}
            <img src="../static/news/images/placeholder-{{ position }}.jpg">
        {% else %}
            <img src="https://picsum.photos/600">
        {% endif %}

        {{ story.content|linebreaks }}
    </div>
</div>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        {% if position < 4 %}
            <img src="../static/news/images/placeholder-{{ position }}.jpg">
        {% else %}
            <img src="https://picsum.photos/600">
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>

she_codes_news/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Dee">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200;400;700&display=swap" rel="stylesheet">        
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}"> 
{% block stylesheets %}        
        <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}
    </head>

    <body>
        <header>
            {% include './nav.html' %}
        </header>
        <div id="title-block">
            <div id="header-text">
                <h1>She Codes News</h1>
            </div>
            <div id="new-story">
                {% if request.user.is_authenticated %}
                    <a class="add-story" href="{% url 'news:newStory'%}">Write New Story</a>
                {% else %}
                    <p class="add-story" id="unlogged">Please login to add a story!</p>
                {% endif %}
            </div>
        </div>
        <div id="menu">
            <a href="{% url 'news:index' %}">LATEST NEWS</a>
            <a href="">CATS</a>
            <a href="">DOGS</a>
        </div>

        

        <!-- content blocks here -->
        {% block content %}{% endblock %}
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <div id="nav-container">
    <img id="she-codes" src="../../static/news/images/shecodes_logo.png">
        {% if request.user.is_authenticated %}
        <div id="navbar">
            <div class="login-links">
                <img class="icon" src="../../static/news/images/user-icon.png">
                <a href="/users/{{ user.id }}/">{{ user.username }}'s Profile</a>
            </div>
            <a href="{% url 'logout' %}">Logout</a>
        </div>
        {% else %}
         <div id="navbar">
            <div class="login-links">
                <img class="icon" src="../../static/news/images/user-icon.png">
                <a href="{% url 'login' %}">Login</a>
            </div>
            <a href="{% url "users:createAccount" %}">Sign up</a>
        </div>
        {% endif %}
        </div>
    </div>
</nav>

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}
<div id="signup-container"> 
    <h2>Create Account</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="button-div">
            <button id="create-account" type="submit">Create Account</button>
        </div>
    </form>
</div>
{% endblock content %}

she_codes_news/users/templates/users/profile.html
<h1> Hi {{ user.username }}! </h1>